plugins {
  id "java"
  id "jacoco"
  id 'net.nemerosa.versioning' version '2.0.0'
}


versioning {
   scm = 'git'
}

allprojects {
    
    apply plugin: 'java'
	apply plugin: 'jacoco'
    
    version = versioning.info.full
    
    repositories {
        mavenCentral()
    }
    
    dependencies {
        implementation 'org.apache.logging.log4j:log4j-api:2.25.1'
        implementation 'org.apache.logging.log4j:log4j-core:2.25.1'
        implementation 'net.jcip:jcip-annotations:1.0'
        implementation 'info.picocli:picocli:2.2.1'
        
        testImplementation 'junit:junit:4.12'
        testImplementation 'org.mockito:mockito-core:1.+'
        testImplementation 'org.powermock:powermock-mockito-release-full:1.+'
        testImplementation 'org.assertj:assertj-core:3.+'
        testImplementation 'org.awaitility:awaitility:3.+'
    }

    test {
        ignoreFailures = true
    }
    
}
project(':mrbotkicore'){

	apply plugin: 'application'
	mainClassName = "core.Main"

    dependencies {
        implementation project(':mrbotkiessentials')
        implementation project(':mrbotkinetwork')
        implementation project(':mrbotkiexample')
        implementation 'commons-cli:commons-cli:1.2+'
    }
    
    sourceSets {
	    main {
	        resources {
	            srcDirs = ["src/main/xml"]
	            includes = ["**/*.xml"]
	        }
	    }
	}

}

task buildBinarys(type: Copy) {
	dependsOn clean
	dependsOn project('mrbotkicore').assembleDist 
	from 'mrbotkicore/build/distributions'
    into 'dist'
}

configure(buildBinarys) {   
    group = 'build'
    description = 'Builds the binarys and deposits them in ./dist'
}

clean {
	delete 'dist/'
} 

project(':mrbotkiessentials'){

	configurations{
	    testArtifacts
	}
	
	task testJar (type: Jar) {
	    baseName = "${project.name}-test"
	    from sourceSets.test.output
	}
	
	artifacts{
	    testArtifacts testJar
	}
}
 
project(':mrbotkinetwork'){

    dependencies {
        implementation project(':mrbotkiessentials')
    }

}

project(':mrbotkiremotecontrol'){

    dependencies {
        implementation project(':mrbotkinetwork')
        implementation project(':mrbotkiessentials')
    }

}

project(':mrbotkitools'){

    dependencies {
        implementation project(':mrbotkiessentials')
        testImplementation 'org.assertj:assertj-core:3.+'
        testImplementation project (path: ":mrbotkiessentials", configuration: 'testArtifacts')
        
    }

}

project(':mrbotkiexample'){

    dependencies {
        implementation project(':mrbotkitools')
        implementation project(':mrbotkiessentials')
    }

}


